config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  # root 'users#new'

  get 'students/index'
  get 'students/show'
  get 'students/new'
  get 'students/edit'
  get 'students/destroy'
  #5

  get 'instructors/index'
  get 'instructors/show'
  get 'instructors/new'
  get 'instructors/edit'
  get 'instructors/destroy'
  #5

  get 'courses/index'
  get 'courses/show'
  get 'courses/new'
  get 'courses/edit'
  get 'courses/destroy'
  #5

  get 'cohorts/index'
  get 'cohorts/show'
  get 'cohorts/new'
  get 'cohorts/create'
  get 'cohorts/edit'
  get 'cohorts/update'
  get 'cohorts/destroy'
  #7

  get 'users/create'
  get 'users/edit'
  get 'users/destory'
  get 'users/show'
  get 'users/index'
  get 'users/new'
  get 'users/update'
  #7
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/instructor.rb
class Instructor < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :users
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
   first_name + ' ' + last_name
 end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  def index
    @cohorts = Cohort.all
  end

  def show
    @cohort = Cohort.find(params[:id])
    #@students = Student.where(cohort_id: params[:id])
    puts @students
  end

  def new
    @cohort = Cohort.new
  end

  def create
Cohort.create(cohort_params)
redirect_to '/cohorts'
  end

  def edit
    @cohort = Cohort.find(params[:id])
  end

  def update
    @cohort = Cohort.find(params[:id])
    @cohort.update(cohort_params)
    redirect_to '/cohorts'
  end

  def destroy
    Cohort.find(params[:id]).destroy
    redirect_to '/cohorts'
  end
  
  private
  def cohort_params
    params.require(:cohort).permit(:name, :start_date, :end_date, :instructor_id, :course_id)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @Courses = Course.all
  end

  def show
@course = Course.find(params[:id])
  end

  def new
    @course = Course.new
  end


  def edit
    @course = Course.find(params[:id])
  end

  def update
@course = Course.find(params[:id])
  @course.update(course_params)
  redirect_to '/courses'
  end

  def destroy
    Course.find(params[:id]).destroy
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  def index
    @instructrs = Instructor.all
  end

  def show
@instructor = Instructor.find(params[:id])
  end

  def new
@instructor = Instructor.new
  end

  def edit
@instructor = Instructor.find(params[:id])
  end

  def update
    @instructor = Instructor.find(params[:id])
      @instructor.update(instructor_params)
      redirect_to '/instructors'
    end 

  def destroy
    Instructor.find(params[:id]).destroy
    redirect_to '/instructors'
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
@student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
@student = Student.find(params[:id])
  @student.update(student_params)
  redirect_to '/students'
  end

  def destroy
    Student.find(params[:id]).destroy
  end

  private
  def student_params
    params.require(:student).permit(:first_name, :last_name, :age, :education, :user_id, :cohort_id, :id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
      # @user = User.all.order("created_at DESC")
      # @user = User.all.order("created_at ASC")
      @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = current_user.users.build
  end

  def create
    @user = current_user.users.build(user_params)

    if @user.save
    redirect_to '/users'
    #root_path
  end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
# @user = User.new(user_params)
if @user.update_attributes(user_params)
redirect_to '/users'
else
render 'edit'
end
  end

  def destroy
    @user = User.destroy(params[:id])
redirect_to '/users'
  end

  private
def user_params
    params.require(:user).permit(:first_name, :last_name, :age)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cohorts/_form.html.erb
<%= form_for @cohort, remote:true do |f| %>
  <%= f.text_field :name, required:true%>

  <%= f.collection_select :educator_id, Educator.order(:last_name), :id,:full_name%>

  <%= f.date_field :start, required:true%>
  <%= f.date_field :end, required:true%>

  <%= f.hidden_field :course_id, value: params[:course_id]%>

  <%= f.submit %>
<% end %>

app/views/cohorts/create.html.erb
<h1>Cohorts#create</h1>
<p>Find me in app/views/cohorts/create.html.erb</p>

<%= form_for @cohort do |f| %>
<%= f.label :name %>
<%= f.text_field :name, value: @cohort.name #,required: true %>

<%= f.label :start %>
<%= f.date_select :select, value: @cohort.start_date %>

<%= f.label :end %>
<%= f.date_select :end, value: @cohort.end_date %>

<%= f.submit %>

app/views/cohorts/destroy.html.erb
<h1>Cohorts#destroy</h1>
<p>Find me in app/views/cohorts/destroy.html.erb</p>

app/views/cohorts/edit.html.erb
<h1>Cohorts#edit</h1>
<p>Find me in app/views/cohorts/edit.html.erb</p>

  <%= form_for @cohort do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name, value: @cohort.name %>

  <%= f.label :start_date %>
  <%= f.text_field :start_date, value: @cohort.start_date%>

  <%= f.label :end_date %>
  <%= f.text_field :end_date, value: @cohort.end_date %>

  <%= f.label :instructor_id %>
  <%= f.collection_select :instructor_id, Instructor.order(:lastname) %>

  <%= f.label :course_id %>
  <%= f.collection_select :course_id, Course.order(:name), :id, :name %>

  <%= f.submit%>


</div>

app/views/cohorts/index.html.erb
<h1>Cohorts#index</h1>
<p>Find me in app/views/cohorts/index.html.erb</p>
<%= link_to("Show", cohorts_index_path, :class => 'action edit') %>
<%= link_to("Edit", cohorts_edit_path, :class => 'action edit') %>

<%= form_for @cohort.each do |f| %>
  <%= f.text_field :name %>
  <%= f.date_field :start, required:true%>
  <%= f.date_field :end, required:true%>
  <%= f.submit %>
<% end %>

app/views/cohorts/new.html.erb
<h1>Cohorts#new</h1>
<p>Find me in app/views/cohorts/new.html.erb</p>
<p>Cohort Name </p>

<%= form_for @cohort.each do |f| %>
<%= f.date_field(:start) %>
<%= f.date_field(:end) %>
<%= f.submit 'Register' %><br>
<% end %>

app/views/cohorts/show.html.erb
<h1>Cohorts#show</h1>
<p>Find me in app/views/cohorts/show.html.erb</p>

<p>Relay with taht pump</p>

app/views/courses/_form.html.erb
<%= form_for @course do |f| %>

<li><%= f.label :name %></li>
<li><%= f.text_field :name %></li>

<li><%= f.number_field :hours %></li>
<li><%= f.label :hours %></li>

<li><%= f.submit %></li>
<% end %>

app/views/courses/destroy.html.erb
<h1>Courses#destroy</h1>
<p>Find me in app/views/courses/destroy.html.erb</p>

app/views/courses/edit.html.erb
<h1>Courses#edit</h1>
<p>Find me in app/views/courses/edit.html.erb</p>

<%= form_for @course |f| %>
<%= f.label :name %>
<%= f.text_field :name, value: @course.name %>
<%= f.label :hours %>
<%= f.number_field :hours, value: @course.hours%>
<%= f.submit %>
<% end %>

app/views/courses/index.html.erb
<h1>Courses#index</h1>
<p>Find me in app/views/courses/index.html.erb</p>
<%= form_for @courses do |u| %>
<%= u.text_field :name %>
<%= u.time :hours %>
<%= link_to("Show", courses_index_path(u), :class => 'action edit')%>
<%= link_to("Edit", courses_edit_path(u), :class => 'action edit') %>
<% end

app/views/courses/new.html.erb
<h1>Courses#new</h1>
<p>Find me in app/views/courses/new.html.erb</p>

app/views/courses/show.html.erb
<h1>Courses#show</h1>
<p>Find me in app/views/courses/show.html.erb</p>

app/views/instructors/destroy.html.erb
<h1>Instructors#destroy</h1>
<p>Find me in app/views/instructors/destroy.html.erb</p>

app/views/instructors/edit.html.erb
<h1>Instructors#edit</h1>
<p>Find me in app/views/instructors/edit.html.erb</p>

app/views/instructors/index.html.erb
<h1>Instructors#index</h1>
<p>Find me in app/views/instructors/index.html.erb</p>
<% form_for @instructors do |f| %>
<%= link_to("Show", cohorts_index_path(f), :class => 'action edit') %>
<%= link_to("Edit", cohorts_edit_path(f), :class => 'action edit') %>

app/views/instructors/new.html.erb
<h1>Instructors#new</h1>
<p>Find me in app/views/instructors/new.html.erb</p>

app/views/instructors/show.html.erb
<h1>Instructors#show</h1>
<p>Find me in app/views/instructors/show.html.erb</p>

app/views/layouts/_header.html.erb
<ul>
<li><%= link_to "Home", users_path %></li><br>
<li><%= link_to "New Course", courses_new_path %></li><br>
<li><%= link_to "New Instructor", instructors_new_path %></li><br>
<li><%= link_to "New Cohort", cohorts_new_path %></li><br>
<li><%= link_to "New Students", students_new_path %></li><br>


<% if user_signed_in? %>
<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li><br>
<% else %>
<li><%= link_to "Sign Up", new_user_registration_path %></li><br>
<li><%= link_to "Log In", new_user_session_path %></li><br>
<% end %>
</ul>

<ul>
<% if user_signed_in? %>
<li><%= link_to "New User", new_user_path %></li><br>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pamelas Panel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<%= render '/layouts/header' %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/students/destroy.html.erb
<h1>Students#destroy</h1>
<p>Find me in app/views/students/destroy.html.erb</p>

app/views/students/edit.html.erb
<h1>Students#edit</h1>
<p>Find me in app/views/students/edit.html.erb</p>

app/views/students/index.html.erb
<h1>Students#index</h1>
<p>Find me in app/views/students/index.html.erb</p>
<%= form_for @students do |f| %>
<%= link_to("Show", cohorts_index_path(f), :class => 'action edit') %>
<%= link_to("Edit", cohorts_edit_path(f), :class => 'action edit') %>
<% end %>

app/views/students/new.html.erb
<h1>Students#new</h1>
<p>Find me in app/views/students/new.html.erb</p>

app/views/students/show.html.erb
<h1>Students#show</h1>
<p>Find me in app/views/students/show.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

<p><%= @user %></p>

app/views/users/destroy.html.erb
<h1>Users#destory</h1>
<p>Find me in app/views/users/destory.html.erb</p>

<p><% @user do |u| %> </p>
<%= u.first_name :first_name %>
<%= u.last_name :last_name %>
<%= u.age :age %>
<%= u.destroy 'Delete' %>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

<h2>edit Book</h2>

<%= form_for @user do |f| %>
<%= f.text_field :first_name, placeholder: "First Name" %><br>
<%= f.text_field :last_name, placeholder: "Last Name" %><br>
<%= f.text_field :age, placeholder: "Age" %><br>
<%= f.submit 'Update' %><br>
<br>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<p>He stay with that pump, Race </p>
<p><% @user.each do |u| %> </p>
<h2><%= link_to "#{u.first_name} #{u.last_name}", user_path(u) %></h2>

<%= link_to("Show", user_path(u), :class => 'action edit')%>
<%= link_to("Edit", edit_user_path(u), :class => 'action edit') %>

<% end %>
<br>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

<%= form_for @user do |f| %>
<%= f.text_field :first_name, placeholder: "First Name" %><br>
<%= f.text_field :last_name, placeholder: "Last Name" %><br>
<%= f.text_field :age, placeholder: "Age" %><br>
<%= f.submit 'Register' %><br>
<br>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<h1><% @user %> </h1>
<%= @user.first_name %><br>
<%= @user.last_name %><br>
<%= @user.age %><br>
<%= link_to "Back", users_path %>
<%= link_to "Edit", edit_user_path(@user) %>
<%= link_to "Delete", user_path(@user), method: :delete, data: { confirm: "Are you sure?" } %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

<%= form_for @user do |f| %>
<%= f.text_field :first_name %><br>
<%= f.text_field :last_name %><br>
<%= f.text_field :age%><br>
<%= f.submit 'Update' %>

<% end %>